"""CDISC Define-XML 2.1 generator.

Produces a minimal but spec-compliant Define-XML 2.1 document documenting
ADaM datasets, parameter codes, and origin information.  Uses only stdlib
``xml.etree.ElementTree`` — no new dependencies.

Refs:
- docs/09-cdisc-support.md §7 — Define-XML generation
- CDISC Define-XML 2.1 specification
- ODM 1.3.2 base standard
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

from pkplugin.cdisc.adam import ADPC_VARIABLES, ADPP_VARIABLES
from pkplugin.cdisc.paramcd import PARAMCD_REGISTRY

# ---------------------------------------------------------------------------
# Namespace declarations required by Define-XML 2.1
# ---------------------------------------------------------------------------

_NS = {
    "def": "http://www.cdisc.org/ns/def/v2.1",
    "odm": "urn:cdisc:odm:v1.3.2",
    "xlink": "http://www.w3.org/1999/xlink",
    "xs": "http://www.w3.org/2001/XMLSchema",
}

# Register namespaces so ET writes them correctly
for _prefix, _uri in _NS.items():
    ET.register_namespace(_prefix, _uri)

# Default dataset metadata
_DATASET_META: dict[str, dict[str, str]] = {
    "ADPC": {
        "label": "Pharmacokinetic Concentration Analysis Dataset",
        "structure": "One record per subject per analyte per time point",
        "class": "BASIC DATA STRUCTURE",
        "purpose": "Analysis",
    },
    "ADPP": {
        "label": "Pharmacokinetic Parameters Analysis Dataset",
        "structure": "One record per subject per parameter",
        "class": "BASIC DATA STRUCTURE",
        "purpose": "Analysis",
    },
}

# Simple column type hints for Define-XML ItemDef DataType attribute
_CHAR_COLS = {
    "STUDYID", "USUBJID", "SUBJID", "SITEID", "AGEU", "SEX", "RACE",
    "ARM", "ARMCD", "ACTARM", "PARAMCD", "PARAM", "AVALC", "AVALU",
    "AVISIT", "ATPT", "ADTM", "ANL01FL", "SAFFL", "ITTFL", "TRTP", "TRTA",
    "PARCAT1", "PARCAT2", "AVALCAT1", "PPCAT", "PPSCAT", "PPSPEC",
    "PPMETHOD", "PPSTRESU", "DTYPE",
}


def _col_datatype(colname: str) -> str:
    return "text" if colname in _CHAR_COLS else "float"


def generate_define_xml(
    study_id: str,
    domains: list[str],
    paramcds_used: list[str],
    output_path: Path,
    *,
    metadata: dict[str, str] | None = None,
) -> Path:
    """Generate a minimal Define-XML 2.1 file.

    Args:
        study_id: STUDYID value used in the datasets.
        domains: ADaM dataset names to document, e.g. ``["ADPC", "ADPP"]``.
        paramcds_used: List of PARAMCD codes present in the datasets.
        output_path: Destination ``.xml`` file path.
        metadata: Optional dict with keys ``study_name``, ``study_description``,
            ``protocol_name``, ``ct_version``.

    Returns:
        Resolved path of the written file.
    """
    meta = metadata or {}
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # -----------------------------------------------------------------------
    # Root ODM element
    # -----------------------------------------------------------------------
    odm_attrs = {
        "xmlns": "urn:cdisc:odm:v1.3.2",
        "xmlns:def": "http://www.cdisc.org/ns/def/v2.1",
        "xmlns:xlink": "http://www.w3.org/1999/xlink",
        "FileType": "Snapshot",
        "FileOID": f"{study_id}.define.xml",
        "CreationDateTime": _utc_now(),
        "AsOfDateTime": _utc_now(),
        "ODMVersion": "1.3.2",
        "def:Context": "PrimaryDataCollection",
    }
    root = ET.Element("ODM", odm_attrs)

    # -----------------------------------------------------------------------
    # Study / GlobalVariables
    # -----------------------------------------------------------------------
    study_el = ET.SubElement(root, "Study", {"OID": f"ST.{study_id}"})
    gv = ET.SubElement(study_el, "GlobalVariables")
    _text_el(gv, "StudyName", meta.get("study_name", study_id))
    _text_el(gv, "StudyDescription", meta.get("study_description", "pk-copilot ADaM datasets"))
    _text_el(gv, "ProtocolName", meta.get("protocol_name", study_id))

    # -----------------------------------------------------------------------
    # MetaDataVersion
    # -----------------------------------------------------------------------
    mdv_oid = f"MDV.{study_id}"
    mdv_attrs = {
        "OID": mdv_oid,
        "Name": "Define-XML generated by pk-copilot v2.0",
        "Description": "ADaM ADPC/ADPP metadata",
        "def:DefineVersion": "2.1.0",
        "def:StandardName": "ADaM",
        "def:StandardVersion": "1.3",
    }
    mdv = ET.SubElement(study_el, "MetaDataVersion", mdv_attrs)

    # -----------------------------------------------------------------------
    # AnnotatedCRF / SupplementalDoc (def: required elements)
    # -----------------------------------------------------------------------
    ET.SubElement(mdv, "def:AnnotatedCRF")
    ET.SubElement(mdv, "def:SupplementalDoc")

    # -----------------------------------------------------------------------
    # ItemGroupDef — one per domain
    # -----------------------------------------------------------------------
    domain_variables: dict[str, list[str]] = {
        "ADPC": ADPC_VARIABLES,
        "ADPP": ADPP_VARIABLES,
    }

    item_refs_by_domain: dict[str, list[ET.Element]] = {}
    all_item_defs: list[ET.Element] = []

    for domain in domains:
        domain_upper = domain.upper()
        if domain_upper not in _DATASET_META:
            continue
        dmeta = _DATASET_META[domain_upper]
        cols = domain_variables.get(domain_upper, [])

        igd_oid = f"IG.{domain_upper}"
        igd_attrs = {
            "OID": igd_oid,
            "Name": domain_upper,
            "Repeating": "Yes",
            "IsReferenceData": "No",
            "SASDatasetName": domain_upper,
            "def:Label": dmeta["label"],
            "def:Structure": dmeta["structure"],
            "def:Class": dmeta["class"],
            "def:Purpose": dmeta["purpose"],
            "def:ArchiveLocationID": f"LF.{domain_upper}",
        }
        igd = ET.SubElement(mdv, "ItemGroupDef", igd_attrs)

        item_refs: list[ET.Element] = []
        for order_num, col in enumerate(cols, start=1):
            item_oid = f"IT.{domain_upper}.{col}"
            ir = ET.SubElement(igd, "ItemRef", {
                "ItemOID": item_oid,
                "OrderNumber": str(order_num),
                "Mandatory": "Yes" if col in ("STUDYID", "USUBJID", "PARAMCD", "AVAL") else "No",
                "KeySequence": "1" if col == "USUBJID" else "",
            })
            item_refs.append(ir)

            # Build ItemDef
            idef = ET.Element("ItemDef", {
                "OID": item_oid,
                "Name": col,
                "DataType": _col_datatype(col),
                "Length": "200" if _col_datatype(col) == "text" else "8",
                "SASFieldName": col[:8],   # SAS limit
                "def:Label": col,
                "def:Origin": "Derived",
            })
            all_item_defs.append(idef)

        item_refs_by_domain[domain_upper] = item_refs

        # def:leaf (archive location)
        ET.SubElement(
            igd,
            "def:leaf",
            {
                "ID": f"LF.{domain_upper}",
                "xlink:href": f"{domain_upper.lower()}.csv",
            },
        )

    # Append ItemDefs to MetaDataVersion
    for idef in all_item_defs:
        mdv.append(idef)

    # -----------------------------------------------------------------------
    # CodeList — PARAMCD
    # -----------------------------------------------------------------------
    if paramcds_used:
        cl = ET.SubElement(mdv, "CodeList", {
            "OID": "CL.PARAMCD",
            "Name": "PARAMCD",
            "DataType": "text",
        })
        for paramcd in sorted(set(paramcds_used)):
            entry = PARAMCD_REGISTRY.get(paramcd.upper())
            if entry is not None:
                clitem = ET.SubElement(cl, "EnumeratedItem", {
                    "CodedValue": entry.paramcd,
                })
                ET.SubElement(clitem, "Decode").text = entry.param

    # -----------------------------------------------------------------------
    # Write to file
    # -----------------------------------------------------------------------
    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(str(output_path), encoding="UTF-8", xml_declaration=True)

    return output_path.resolve()


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def _utc_now() -> str:
    """Return current UTC datetime as ISO 8601 string (no sub-second)."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _text_el(parent: ET.Element, tag: str, text: str) -> ET.Element:
    el = ET.SubElement(parent, tag)
    el.text = text
    return el
